# Generated by Django 3.1.1 on 2020-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
